"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { FileText, Loader2, RefreshCw } from "lucide-react";
import { useLatestDigest, useDigests, generateDigest } from "@/lib/pm-api";

export function DigestPanel() {
  const { data: latest, isLoading: loadingLatest, error } = useLatestDigest();
  const { data: digests, isLoading: loadingList } = useDigests(5);
  const [generating, setGenerating] = useState(false);
  const [genError, setGenError] = useState<string | null>(null);

  const handleGenerate = async () => {
    setGenerating(true);
    setGenError(null);
    try {
      await generateDigest(false);
    } catch (e) {
      setGenError(e instanceof Error ? e.message : "Failed to generate digest");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-sm font-medium">Latest Digest</h3>
          <p className="text-xs text-muted-foreground">
            Portfolio summary generated by the PM engine
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          className="h-8 text-xs"
          onClick={handleGenerate}
          disabled={generating}
        >
          {generating ? (
            <><Loader2 className="h-3 w-3 mr-1 animate-spin" /> Generating…</>
          ) : (
            <><RefreshCw className="h-3 w-3 mr-1" /> Generate Digest</>
          )}
        </Button>
      </div>

      {genError && (
        <div className="rounded-md border border-red-500/30 bg-red-50 px-4 py-3 text-sm text-red-600">
          {genError}
        </div>
      )}

      {error && !loadingLatest && (
        <Card>
          <CardContent className="py-8 text-center">
            <FileText className="h-8 w-8 text-muted-foreground mx-auto mb-2" />
            <p className="text-sm text-muted-foreground">
              No digest generated yet. Click &quot;Generate Digest&quot; to create one.
            </p>
          </CardContent>
        </Card>
      )}

      {loadingLatest && (
        <Card>
          <CardContent className="space-y-3 py-4">
            <Skeleton className="h-6 w-1/3" />
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-2/3" />
          </CardContent>
        </Card>
      )}

      {latest && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-xs text-muted-foreground flex items-center gap-1">
              <FileText className="h-3 w-3" />
              {latest.digest_id}
              {latest.polished && (
                <span className="text-[10px] text-emerald-600 ml-1">polished</span>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="prose prose-sm prose-invert max-w-none [&_h1]:text-base [&_h1]:font-semibold [&_h2]:text-sm [&_h2]:font-semibold [&_h3]:text-sm [&_p]:text-sm [&_li]:text-sm [&_table]:text-xs">
              <ReactMarkdown>{latest.markdown}</ReactMarkdown>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Recent digests */}
      {digests && digests.length > 1 && (
        <div>
          <p className="text-xs text-muted-foreground mb-2">Recent Digests</p>
          <div className="space-y-1">
            {digests.slice(0, 5).map((d) => (
              <div
                key={d.digest_id}
                className="flex items-center justify-between text-xs px-3 py-2 rounded-md border border-border"
              >
                <div className="flex items-center gap-2">
                  <FileText className="h-3 w-3 text-muted-foreground" />
                  <span>{d.digest_id}</span>
                </div>
                <div className="flex items-center gap-3 text-muted-foreground">
                  <span>{d.total_active} active</span>
                  {d.red_count > 0 && <span className="text-red-600">{d.red_count} red</span>}
                  {d.ceo_attention_count > 0 && (
                    <span className="text-amber-600">{d.ceo_attention_count} CEO</span>
                  )}
                  <span>{new Date(d.generated_at).toLocaleDateString([], { month: "short", day: "numeric" })}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
